name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          ca-certificates \
          gnupg \
          lsb-release \
          software-properties-common
        # Add PostgreSQL official repository
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
        sudo apt-get update
        # Try PostgreSQL 17 first, fallback to 16 if not available
        sudo apt-get install -y \
          postgresql-17 postgresql-server-dev-17 postgresql-client-17 \
          || sudo apt-get install -y \
          postgresql-16 postgresql-server-dev-16 postgresql-client-16 \
          || sudo apt-get install -y \
          postgresql-15 postgresql-server-dev-15 postgresql-client-15
        sudo apt-get install -y \
          build-essential \
          make \
          gcc \
          libc6-dev \
          pkg-config \
          libpq-dev

    - name: Build all components
      run: |
        cd pgraft && make clean && make
        cd ../ramd && make clean && make
        cd ../ramctrl && make clean && make

    - name: Create release package
      run: |
        mkdir -p release
        cp pgraft/pgraft.so release/
        cp ramd/ramd release/
        cp ramctrl/ramctrl release/
        cp -r pgraft/sql release/
        cp README.md release/
        cp pgraft/README.md release/pgraft-README.md
        cp ramd/README.md release/ramd-README.md
        cp ramctrl/README.md release/ramctrl-README.md
        tar -czf ram-release-${GITHUB_REF_NAME}.tar.gz -C release .
        echo "Release package created: ram-release-${GITHUB_REF_NAME}.tar.gz"

    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-package
        path: ram-release-*.tar.gz
