name: Comprehensive Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          postgresql-17 \
          postgresql-server-dev-17 \
          postgresql-client-17 \
          build-essential \
          make \
          gcc \
          libc6-dev \
          pkg-config \
          libpq-dev \
          valgrind \
          cppcheck

    - name: Build all components
      run: |
        make all

    - name: Install pgraft extension
      run: |
        cd pgraft
        sudo make install

    - name: Test pgraft extension
      run: |
        sudo -u postgres psql -d testdb -c "CREATE EXTENSION IF NOT EXISTS pgraft;"
        sudo -u postgres psql -d testdb -c "SELECT pgraft_version();" || echo "pgraft_version function not available"
        echo "pgraft extension test completed"


    - name: Run static analysis
      run: |
        if command -v cppcheck >/dev/null 2>&1; then
          cppcheck --enable=all --inconclusive --std=c99 --suppress=missingIncludeSystem pgraft/src/ ramd/src/ ramctrl/src/ 2>&1 || true
        else
          echo "cppcheck not available, skipping static analysis"
        fi

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          pgraft/valgrind-out.txt
          */test-results.txt
